# Comitards data, hard-coded baby
people = {'10aZd': {'age': None, #Done
                    'description': 'en couple avec médusa',
                    'height': '',
                    'name': 'Erwan Boultouak',
                    'pictures': ['static/corbax_1.jpeg'],
                    'post': 'Quinzaine',
                    'nickname': 'Corbax',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          '123abc': {'age': 3.14,
                     'description': "J'aime la chope et la guindaille. Yahouuuu",
                     'height': '3 futs',
                     'name': 'Camart',
                     'pictures': ['static/1.jpg',
                                  'static/2.jpg',
                                  'static/3.jpg',
                                  'static/4.jpg',
                                  'static/3.jpg',
                                  'static/2.jpg',
                                  'static/1.jpg'],
                     'post': 'Sys admin',
                     'nickname': 'Camartichau',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          '62Emn': {'age': '19', #Done
                    'description': 'coincoin, soit a louv soit a liège',
                    'height': '187',
                    'name': 'Léo Deverd',
                    'pictures': ['static/Léo_1.jpeg'],
                    'post': 'Cyclofette',
                    'nickname': 'π',
                    'star': '2',
                    'favorite_beer': 'Triple Karmeliet',
                    'citation': 'Si je m\'en souviens pas, c\'est que c\'est pas arrivé.'},
          '6nNqD': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Tom delhaye',
                    'pictures': [],
                    'post': 'Kfet',
                    'nickname': 'Copyright',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'AEasF': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Pas assigné, envoie moi ton qr fdp',
                    'pictures': [],
                    'post': '',
                    'nickname': '',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'AVTw1': {'age': None, #Done
                    'description': 'Presque aussi aigrie que la légende le raconte ',
                    'height': '',
                    'name': 'Héloïse Roeland',
                    'pictures': ['static/electrabelle_1.jpeg'],
                    'post': 'Cubix',
                    'nickname': 'Electrabelle',
                    'star': '5',
                    'favorite_beer': 'Tarot d’or',
                    'citation': 'J’ai mal au genou'},
          'AqWL6': {'age': None, #Done
                    'description': 'Yorkmouth',
                    'height': '',
                    'name': 'Rebecca Doubravova',
                    'pictures': ['static/rebek_1.jpeg',
                                 'static/rebek_2.jpeg',
                                 'static/rebek_3.jpeg',
                                 'static/rebek_4.jpeg',
                                 'static/rebek_5.jpeg',
                                 'static/rebek_6.jpeg'],
                    'post': 'Kfet',
                    'nickname': 'Yorkmouth',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'FARkU': {'age': None, #Done
                    'description': 'rot et pet',
                    'height': '',
                    'name': 'Carole Vinesse',
                    'pictures': [],
                    'post': 'Cubix et guindaille 2.0',
                    'nickname': 'Failaibak',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'JVqFL': {'age': None, #Done
                    'description': 'Insta : mia_lrx, Citation : Miguel',
                    'height': '',
                    'name': 'Mia Elena Leroux Visnjic',
                    'pictures': [],
                    'post': 'Bar',
                    'nickname': 'De Vinci',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'LTVrp': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Clarris Gato',
                    'pictures': [],
                    'post': 'Vieux',
                    'nickname': 'Otto',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'LkHOK': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Tatiana Baccus',
                    'pictures': [],
                    'post': 'Quinzaine',
                    'nickname': 'Bacc14',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'Lu8Eq': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Pas assigné, envoie moi ton qr fdp',
                    'pictures': [],
                    'post': '',
                    'nickname': '',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'M4o9f': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Nicolas Rachid',
                    'pictures': [],
                    'post': 'Revue',
                    'nickname': 'KKhuete',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'MRioN': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Pas assigné, envoie moi ton qr fdp',
                    'pictures': [],
                    'post': '',
                    'nickname': '',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'NmhG9': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Alexandre Sanchez',
                    'pictures': ['static/sanchez_1.jpg'],
                    'post': 'Vice president',
                    'nickname': 'Tranquilou Debout',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'Nwtgf': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Louvain Di Cola',
                    'pictures': [],
                    'post': 'Quinzaine',
                    'nickname': 'Gi²',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'Osgqr': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Lisa Rignanese',
                    'pictures': ['static/lisa_1.jpeg',
                                 'static/lisa_2.jpeg',
                                 'static/lisa_3.jpeg',
                                 'static/lisa_4.jpeg',
                                 'static/lisa_5.jpg'],
                    'post': 'Revue',
                    'nickname': 'Danse',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'QDWgd': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Elsa Biver',
                    'pictures': [],
                    'post': 'Présidente',
                    'nickname': 'Panos',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'QXoUB': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Xavier Sanchez-Rivas',
                    'pictures': ['static/4.jpg',
                                 'static/uno_1.jpg',
                                 'static/uno_2.jpg'],
                    'post': 'Grand Maître',
                    'nickname': 'Uno',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'R7omt': {'age': None, #Done
                    'description': 'Jogame la crème de la crème',
                    'height': '',
                    'name': 'Joshua Nerenhausen',
                    'pictures': ['static/Jogame_1.jpg'],
                    'post': 'Chef Bar',
                    'nickname': 'Rhésus',
                    'star': '3',
                    'favorite_beer': 'La Troublette',
                    'citation': 'Plaisir, joie et bonne humeur'},
          'TpB4B': {'age': None, #Done
                    'description': 'Insta: lea_pinter._',
                    'height': '',
                    'name': 'Léa Pinter',
                    'pictures': ['static/lea_1.jpeg',
                                 'static/lea_2.jpeg',
                                 'static/lea_3.jpeg',
                                 'static/lea_4.jpeg',
                                 'static/lea_5.jpeg',
                                 'static/lea_6.jpeg',
                                 'static/lea_7.jpeg'],
                    'post': 'Kfet',
                    'nickname': 'Aerschot',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'Uy2mM': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Nael Bonnarens',
                    'pictures': [],
                    'post': 'Bar',
                    'nickname': 'Vaillant',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'Vhe47': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Pas assigné, envoie moi ton qr fdp',
                    'pictures': [],
                    'post': '',
                    'nickname': '',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'WlI2Q': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Pas assigné, envoie moi ton qr fdp',
                    'pictures': [],
                    'post': '',
                    'nickname': '',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'XngSl': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Pas assigné, envoie moi ton qr fdp',
                    'pictures': [],
                    'post': '',
                    'nickname': '',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'aFIiR': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Clara Horréard',
                    'pictures': ['static/passpar_1.jpeg'],
                    'post': 'Clash',
                    'nickname': 'Passe Partout',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'gsmdj': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Sascha Kurochkin',
                    'pictures': ['static/viggo_1.jpeg',
                                 'static/viggo_2.jpeg',
                                 'static/viggo_3.jpeg'],
                    'post': 'Vice président de baptême',
                    'nickname': 'Viggo',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'h4OXo': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Victor vanden durpel',
                    'pictures': [],
                    'post': 'Cyclofette',
                    'nickname': 'Medusa',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'huTk6': {'age': 'Vieille', #Done
                    'description': '',
                    'height': '3 pommes et demi',
                    'name': 'Zoé Demo',
                    'pictures': ['static/Zoé_1.jpg',
                                 'static/Zoé_2.jpeg'],
                    'post': 'Cheffe cyclofette',
                    'nickname': 'Ephec',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'jTev1': {'age': None, #Done
                    'description': 'Hugo de la bouteille',
                    'height': '',
                    'name': 'Hugo wouters',
                    'pictures': [],
                    'post': 'Quinzaine',
                    'nickname': '2 blouses',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'myXzk': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Matteo Deléhouzée',
                    'pictures': [],
                    'post': 'Facultaire et guindaille 2.0',
                    'nickname': 'Marylin Manson',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'ng6US': {'age': None,#Done
                    'description': '',
                    'height': '',
                    'name': 'Neira Hotilovac',
                    'pictures': [],
                    'post': 'Presidente de baptême',
                    'nickname': 'Random',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'ogkHS': {'age': None, #Done
                    'description': 'Son mec aimerait bien être dominé',
                    'height': '',
                    'name': 'Natasha Loquet',
                    'pictures': [],
                    'post': 'Event',
                    'nickname': 'Jeanne d\'Arc',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'sb3Zu': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Maxence Dronneau',
                    'pictures': ['static/NA_1.jpg',
                                 'static/NA_2.jpg'],
                    'post': 'Bar',
                    'nickname': 'Nageoire Avant',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'sygnw': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Cyril Ducarme',
                    'pictures': [],
                    'post': 'Clash',
                    'nickname': 'Fouras',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'tiPMP': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Juliette Louant',
                    'pictures': ['static/poussin_1.jpeg',
                                 'static/poussin_2.jpeg',
                                 'static/poussin_3.jpeg'],
                    'post': 'Cyclofette',
                    'nickname': 'Poussin',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'vMHet': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Raphaël Veithen',
                    'pictures': [],
                    'post': 'Vice-président de baptême',
                    'nickname': 'Gogh Van clash',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'w0bBg': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Louise Leclère',
                    'pictures': ['static/SM_1.jpg',
                                 'static/SM_2.JPG',
                                 'static/SM_3.JPG'],
                    'post': 'Revue',
                    'nickname': 'Sainte Marthe',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'zZoQK': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Clara de Temmerman',
                    'pictures': [],
                    'post': 'Kfet',
                    'nickname': 'Armageddon',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''},
          'zdidQ': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Espen van de velde',
                    'pictures': ['static/espen_1.jpeg'],
                    'post': 'Cyclofette',
                    'nickname': 'Brice Corléone',
                    'star': '',
                    'favorite_beer': '',
                    'citation': ''}}


# Pas encore bon:  Emilie, louis verhelst, alicia, GLM, Camart, lola
