# Comitards data, hard-coded baby
people = {'10aZd': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Louvent Di Cola',
                    'pictures': [],
                    'post': 'Kfet'},
          '123abc': {'age': 3.14,
                     'description': "J'aime la chope et la guindaille. Yahouuuu",
                     'height': '3 futs',
                     'name': 'Camart',
                     'pictures': ['static/1.jpg',
                                  'static/2.jpg',
                                  'static/3.jpg',
                                  'static/4.jpg',
                                  'static/3.jpg',
                                  'static/2.jpg',
                                  'static/1.jpg'],
                     'post': 'Sys admin'},
          '62Emn': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Alexandre Sanchez',
                    'pictures': [],
                    'post': 'Vice Présidente'},
          '6nNqD': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Mia Elena Leroux Visnjic',
                    'pictures': [],
                    'post': 'Bar'},
          'AEasF': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Victor Vanden Durpel',
                    'pictures': [],
                    'post': 'Cyclofette'},
          'AVTw1': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Emilie Strimelle',
                    'pictures': [],
                    'post': 'Cheffe quinzaine'},
          'AqWL6': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Maxence Dronneau',
                    'pictures': [],
                    'post': 'Bar'},
          'FARkU': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Florian Boon',
                    'pictures': [],
                    'post': 'Trésorier'},
          'JVqFL': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Sascha Kurochkin',
                    'pictures': [],
                    'post': 'Vice-président de baptême'},
          'LTVrp': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Lucie Tournay',
                    'pictures': [],
                    'post': 'Quinzaine'},
          'LkHOK': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Léa Pinter',
                    'pictures': [],
                    'post': 'Kfet'},
          'Lu8Eq': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Matteo Deléhouzée',
                    'pictures': [],
                    'post': 'Facultaire'},
          'M4o9f': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Tatiana Baccus',
                    'pictures': [],
                    'post': 'Quinzaine'},
          'MRioN': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Neira Hotilovac',
                    'pictures': [],
                    'post': 'Présidente de baptême'},
          'NmhG9': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Juliette Louant',
                    'pictures': [],
                    'post': 'Cyclofette'},
          'Nwtgf': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Nicolas Rachid',
                    'pictures': [],
                    'post': 'Revue'},
          'Osgqr': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Joshua Nerenhausen',
                    'pictures': [],
                    'post': 'Chef Bar'},
          'QDWgd': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Henri Pihet',
                    'pictures': [],
                    'post': 'Web'},
          'QXoUB': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Erwan Boultouak',
                    'pictures': [],
                    'post': 'Chef Cyclofette'},
          'R7omt': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Héloïse Roeland',
                    'pictures': [],
                    'post': 'Cubix'},
          'TpB4B': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Hugo Wouters',
                    'pictures': [],
                    'post': 'Quinzaine'},
          'Uy2mM': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Carole Vinesse',
                    'pictures': [],
                    'post': 'Cubix'},
          'Vhe47': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Natacha Loquet',
                    'pictures': [],
                    'post': 'Event'},
          'WlI2Q': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Clara Horréard',
                    'pictures': [],
                    'post': 'Clash'},
          'XngSl': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Louis Verhelst',
                    'pictures': [],
                    'post': 'Bar'},
          'aFIiR': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Lisa Rignanese',
                    'pictures': [],
                    'post': 'Revue'},
          'gsmdj': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Cyril Ducarme',
                    'pictures': [],
                    'post': 'Clash'},
          'h4OXo': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Louise Leclère ',
                    'pictures': [],
                    'post': 'Revue'},
          'huTk6': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Xavier Sanchez-Rivas',
                    'pictures': [],
                    'post': 'Grand-Maitre'},
          'jTev1': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Rebeka Doubravova',
                    'pictures': [],
                    'post': 'Kfet'},
          'myXzk': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Lola Gillet',
                    'pictures': [],
                    'post': 'Kfet'},
          'ng6US': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Clarisse Gatot',
                    'pictures': [],
                    'post': 'Vieux'},
          'ogkHS': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Tom Delhaye',
                    'pictures': [],
                    'post': 'Chef kfet'},
          'sb3Zu': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Léo Deverd',
                    'pictures': [],
                    'post': 'Cyclofette'},
          'sygnw': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Elsa Biver',
                    'pictures': [],
                    'post': 'Présidente'},
          'tiPMP': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Isaline De Saffel',
                    'pictures': [],
                    'post': 'Quinzaine'},
          'vMHet': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Raphaël Veithen',
                    'pictures': [],
                    'post': 'Vice-président de baptême'},
          'w0bBg': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Zoé Demo',
                    'pictures': [],
                    'post': 'Cyclofette'},
          'zZoQK': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Naël Bonnarens',
                    'pictures': [],
                    'post': 'Bar'},
          'zdidQ': {'age': None,
                    'description': '',
                    'height': '',
                    'name': 'Alicia De Hert',
                    'pictures': [],
                    'post': 'Secrétaire'}}
