# Comitards data, hard-coded baby
people = {'10aZd': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Erwan Boultouak',
                    'pictures': [],
                    'post': 'Chef Cyclofette'},
          '123abc': {'age': 3.14,
                     'description': "J'aime la chope et la guindaille. Yahouuuu",
                     'height': '3 futs',
                     'name': 'Camart',
                     'pictures': ['static/1.jpg',
                                  'static/2.jpg',
                                  'static/3.jpg',
                                  'static/4.jpg',
                                  'static/3.jpg',
                                  'static/2.jpg',
                                  'static/1.jpg'],
                     'post': 'Sys admin'},
          '62Emn': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Léo Deverd',
                    'pictures': [],
                    'post': 'Cyclofette'},
          '6nNqD': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Tom delhaye',
                    'pictures': [],
                    'post': 'Bar'},
          'AEasF': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Victor Vanden Durpel',
                    'pictures': [],
                    'post': 'Cyclofette'},
          'AVTw1': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Héloïse Roeland',
                    'pictures': [],
                    'post': 'TODO'},
          'AqWL6': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Rebecca Doubravova',
                    'pictures': [],
                    'post': 'Kfet'},
          'FARkU': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Carole Vinesse',
                    'pictures': [],
                    'post': 'Cubix'},
          'JVqFL': {'age': None, #Done
                    'description': 'Insta : mia_lrx, Citation : Miguel',
                    'height': '',
                    'name': 'Mia Elena Leroux Visnjic',
                    'pictures': [],
                    'post': 'Bar'},
          'LTVrp': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Clarris Gato',
                    'pictures': [],
                    'post': 'Vice présidente de baptême'},
          'LkHOK': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Tatiana Baccus',
                    'pictures': [],
                    'post': 'Quinzaine'},
          'Lu8Eq': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Matteo Deléhouzée',
                    'pictures': [],
                    'post': 'Facultaire'},
          'M4o9f': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Nicolas Rachid',
                    'pictures': [],
                    'post': 'Revue'},
          'MRioN': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Neira Hotilovac',
                    'pictures': [],
                    'post': 'Présidente de baptême'},
          'NmhG9': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Alexandre Sanchez',
                    'pictures': [],
                    'post': 'Vice president'},
          'Nwtgf': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Louvain Di Cola',
                    'pictures': [],
                    'post': 'Kfet'},
          'Osgqr': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Lisa Rignanese',
                    'pictures': [],
                    'post': 'Revue'},
          'QDWgd': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Elsa Biver',
                    'pictures': [],
                    'post': 'Présidente'},
          'QXoUB': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Xavier Sacnhez-Rivas',
                    'pictures': [],
                    'post': 'Grand Maître'},
          'R7omt': {'age': None, #Done
                    'description': 'insta: josh_nrhsn PS: le gros dégueulasse est célibataire',
                    'height': '',
                    'name': 'Joshua Nerenhausen',
                    'pictures': [],
                    'post': 'Chef Bar'},
          'TpB4B': {'age': None, #Done
                    'description': 'Insta: lea_pinter._',
                    'height': '',
                    'name': 'Léa Pinter',
                    'pictures': [],
                    'post': 'Kfet'},
          'Uy2mM': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Nael Bonnarens',
                    'pictures': [],
                    'post': 'Bar'},
          'Vhe47': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Natacha Loquet',
                    'pictures': [],
                    'post': 'Event'},
          'WlI2Q': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Clara Horréard',
                    'pictures': [],
                    'post': 'Clash'},
          'XngSl': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Louis Verhelst',
                    'pictures': [],
                    'post': 'Bar'},
          'aFIiR': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Clara Horréard',
                    'pictures': [],
                    'post': 'Clash'},
          'gsmdj': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Sascha Kurochkin',
                    'pictures': [],
                    'post': 'Vice président de baptême'},
          'h4OXo': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Victor vanden durpel',
                    'pictures': [],
                    'post': 'Cyclofette'},
          'huTk6': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Zoé Demo',
                    'pictures': [],
                    'post': 'Cheffe cyclofette'},
          'jTev1': {'age': None, #Done
                    'description': 'Hugo de la bouteille',
                    'height': '',
                    'name': 'Hugo wouters',
                    'pictures': [],
                    'post': 'Quinzaine'},
          'myXzk': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Matteo Deléhouzée',
                    'pictures': [],
                    'post': 'Facultaire'},
          'ng6US': {'age': None,#Done
                    'description': '',
                    'height': '',
                    'name': 'Neira Hotilovac',
                    'pictures': [],
                    'post': 'Presidente de baptême'},
          'ogkHS': {'age': None, #Done
                    'description': 'Son mec aimerait bien être dominé',
                    'height': '',
                    'name': 'Natasha Loquet',
                    'pictures': [],
                    'post': 'Event'},
          'sb3Zu': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Maxence Dronneau',
                    'pictures': [],
                    'post': 'Bar'},
          'sygnw': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Cyril Ducarme',
                    'pictures': [],
                    'post': 'Clash'},
          'tiPMP': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Juliette Louant',
                    'pictures': [],
                    'post': 'Quinzaine'},
          'vMHet': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Raphaël Veithen',
                    'pictures': [],
                    'post': 'Vice-président de baptême'},
          'w0bBg': {'age': None, #NOK
                    'description': '',
                    'height': '',
                    'name': 'Zoé Demo',
                    'pictures': [],
                    'post': 'Cyclofette'},
          'zZoQK': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Clara de Temmerman',
                    'pictures': [],
                    'post': 'TODO'},
          'zdidQ': {'age': None, #Done
                    'description': '',
                    'height': '',
                    'name': 'Espen van de velde',
                    'pictures': [],
                    'post': 'Cyclofette'}}


# Pas encore bon:  Emilie, louis verhelst, alicia, GLM, Camart, lola, louise leclère